routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::group([
    'middleware' => ['auth']
], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    // Note Routes
    Route::group([
        'as'            => 'note.',
        'prefix'        => 'notes'
    ], function () {
        Route::get('/', [NoteController::class, 'overview'])->name('list');
        Route::get('/create', [NoteController::class, 'create'])->name('create');
        Route::get('/{note_id}', [NoteController::class, 'view'])->name('view');
        Route::post('/{note_id?}', [NoteController::class, 'store'])->name('store');
    });

    // Category Routes
       Route::group([
        'as'            => 'category.',
        'prefix'        => 'categories'
    ], function () {
        Route::get('/', [CategoryController::class, 'overview'])->name('list');
        Route::get('/create', [CategoryController::class, 'create'])->name('create');
        Route::get('/{category_id}', [CategoryController::class, 'view'])->name('view');
        Route::post('/{category_id?}', [CategoryController::class, 'store'])->name('store');
    });
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <ul class="list-inline">
                    <li class="list-inline-item"> <a href="{{ route('note.list') }}">{{ __('View Notes') }}</a></li>
                    <li class="list-inline-item"> | <a href="{{ route('category.list') }}">{{ __('View Note Categories') }}</a></li>
                    </ul>
                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection