routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::group([
    'middleware' => ['auth']
], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    // Note Routes
    Route::group([
        'as'            => 'note.',
        'prefix'        => 'notes'
    ], function () {
        Route::get('/', [NoteController::class, 'overview'])->name('list');
        Route::get('/create', [NoteController::class, 'create'])->name('create');
        Route::get('/{note_id}', [NoteController::class, 'view'])->name('view');
        Route::post('/{note_id?}', [NoteController::class, 'store'])->name('store');
    });

    // Category Routes
       Route::group([
        'as'            => 'category.',
        'prefix'        => 'categories'
    ], function () {
        Route::get('/', [CategoryController::class, 'overview'])->name('list');
        Route::get('/create', [CategoryController::class, 'create'])->name('create');
        Route::get('/{category_id}', [CategoryController::class, 'view'])->name('view');
        Route::post('/{category_id?}', [CategoryController::class, 'store'])->name('store');
    });
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

     //return the notes
     public function notes()
     {
         return $this->belongsToMany(Note::class, 'note_categories');
     }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Auth;

use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display list of category
     */
    public function overview()
    {
        try{
            $categories = Category::where('user_id', Auth::id())->get();

            return view(
                'category.list',
                compact(
                    'categories'
                )
            );
        }
        catch(\Exception $e){
            return back()->with("error-message", "Something went wrong...".$e->getMessage());
        }
    }
    /**
     * show form for creating category
     */
    public function create()
    {
        return view('category.form');
    }
    /**
     * display category for update
     */
    public function view()
    {
        try{
            $category = Category::where('id', request('category_id'))
                ->where('user_id', Auth::id())
                ->firstOrFail();
                
            return view(
                'category.form',
                compact('category')
            );
        }
        catch(\Exception $e){
            return back()->with("error-message", "Something went wrong...".$e->getMessage());
        }
      
    }
    /**
     * creating a new category
     */
    public function store(CategoryRequest $request)
    {
        try{
            $validated = $request->validated();

            $category = Category::where('id', request('category_id'))
                ->where('user_id', Auth::id())
                ->first();
    
            if (!$category) {
                $category = new Category();
            }
    
            $validated['user_id'] = Auth::id();
            $category->fill($validated);
            $category->save();
    
            return redirect(route('category.list'))->with('status', 'Category Saved Successfully!');
        }
        catch(\Exception $e){
            return back()->with("error-message", "Something went wrong...".$e->getMessage());
        }
    }

}

resources/views/category/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">

        <div class="col-md-8">

            <div class="card">

                <div class="card-header">{{ __(isset($category) ? 'Edit Category' : 'Create Category') }} <a href="{{ route('category.list') }}" class="float-right btn btn-primary btn-sm">{{ __('Category List') }}</a> </div>

                <div class="card-body">
                    @if (session('error-message'))
                        <div class="alert alert-danger" role="alert">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ session('error-message') }}
                        </div>
                    @endif

                    <form action="{{ isset($category) ? route('category.store', $category->id) : route('category.store') }}" method="post">
                        @csrf

                        <div class="form-group">
                            <label for="name">{{ __('Category Name') }}*</label>
                            <input type="text" name="name" id="name" placeholder="Category Name" class="form-control @error('name') is-invalid @enderror" value="{{ isset($category) ? $category->name : old('name') }}">

                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>

                        <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
                    </form>

                </div>

            </div>

        </div>

    </div>

</div>

@endsection

resources/views/category/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Categories') }}<a href="{{ route('category.create') }}" class="float-right btn btn-primary btn-sm">{{ __('Create Category') }}</a></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                         <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ session('status') }}
                        </div>
                    @endif
                    @if (session('error-message'))
                        <div class="alert alert-danger" role="alert">
                           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ session('error-message') }}
                        </div>
                    @endif

                    <ul class="list-group list-group-flush">
                        @forelse ($categories as $category)
                            <li class="list-group-item"><a href="{{ route('category.view', $category->id) }}">{{ $category->name }}</a></li>
                        @empty
                        <em>No category available, click here to <a href="{{ route('category.create') }}">{{ __('Create Category') }}</a></em>
                        @endforelse
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection