routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::group([
    'middleware' => ['auth']
], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    // Note Routes
    Route::group([
        'as'            => 'note.',
        'prefix'        => 'notes'
    ], function () {
        Route::get('/', [NoteController::class, 'overview'])->name('list');
        Route::get('/create', [NoteController::class, 'create'])->name('create');
        Route::get('/{note_id}', [NoteController::class, 'view'])->name('view');
        Route::post('/{note_id?}', [NoteController::class, 'store'])->name('store');
    });

    // Category Routes
       Route::group([
        'as'            => 'category.',
        'prefix'        => 'categories'
    ], function () {
        Route::get('/', [CategoryController::class, 'overview'])->name('list');
        Route::get('/create', [CategoryController::class, 'create'])->name('create');
        Route::get('/{category_id}', [CategoryController::class, 'view'])->name('view');
        Route::post('/{category_id?}', [CategoryController::class, 'store'])->name('store');
    });
});

app/Models/Note.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    //return the categories
    public function categories()
    {
        return $this->belongsToMany(Category::class, 'note_categories');
    }
    
    //assign a category to a note
    public function assignCategory($category)
    {
      //  if(!$this->hasCategory($category)){
            if (is_string($category)) {
                return $this->categories()->save(
                    Category::whereName($category)->firstOrFail()
                );
            } 
            return $this->categories()->save($category);
       // }
    }

    //has category
    public function hasCategory($category)
    {
        if (is_string($category)) {
            return !! $this->categories()->whereName($category)->first();
        }
        return !! $this->categories->find($category);
    } 

}

app/Http/Controllers/NoteController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\NoteRequest;
use App\Models\Note;
use App\Models\Category;
use App\Models\NoteCategory;
use Auth;
use Illuminate\Http\Request;

class NoteController extends Controller
{
    public function overview()
    {
        try{
            $notes = Note::with(['categories'])->where('user_id', Auth::id())->get();

            return view(
                'note.list',
                compact(
                    'notes'
                )
            );
        }
        catch(\Exception $e){
            return back()->with("error-message", "Something went wrong...".$e->getMessage());
        }
    }

    public function create()
    {
         try{
            $categories = Category::where('user_id', Auth::id())->get();
            return view(
                'note.form',
                compact('categories')
            );
        }
        catch(\Exception $e){
            return back()->with("error-message", "Something went wrong...".$e->getMessage());
        }
    }

    public function view()
    {
        try{
            $note_id = request('note_id');
            $note = Note::where('id', $note_id)
                ->where('user_id', Auth::id())
                ->firstOrFail();

            $categories = Category::where('user_id', Auth::id())->get();
            $existingNoteCategories = NoteCategory::where('note_id', $note_id)->pluck('category_id')->toArray();
                
            return view(
                'note.form',
                compact('note','categories','existingNoteCategories')
            );
        }
        catch(\Exception $e){
            return back()->with("error-message", "Something went wrong...".$e->getMessage());
        }
    }

    public function store(NoteRequest $request)
    {
       try{
         $validated = $request->validated();
         \DB::transaction(function () use($validated,$request){

                $note = Note::where('id', request('note_id'))
                    ->where('user_id', Auth::id())
                    ->first();

                if (!$note) {
                    $note = new Note();
                }

                $validated['user_id'] = Auth::id();
                $note->fill($validated);
                $note->save();

                //adding note category
                $selectedCategories = request('note_categories')?:array();
                $noteCategoryArray = array();
                $activityTime = $note->created_at;

                    foreach($selectedCategories as $category_id){
                    // $category = Category::find($category_id);
                    // $note->assignCategory($category);
                        $noteCategoryArray[] = [
                            "note_id" => $note->id,
                            "category_id" => $category_id,
                            "created_at" => $activityTime,
                            "updated_at" => $activityTime
                        ];
                    }
                    //create new note-category
                    NoteCategory::insertOrIgnore($noteCategoryArray);
                    //delete categories not selected
                    NoteCategory::where('note_id',$note->id)->whereNotIn('category_id',$selectedCategories)->delete();
            });

            return redirect(route('note.list'))->with('status', 'Note Saved');
        }
        catch(\Exception $e){
            return back()->with("error-message", "Something went wrong...".$e->getMessage());
        }
    }


}

resources/views/note/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">

        <div class="col-md-8">

            <div class="card">

                <div class="card-header">{{ __(isset($note) ? 'Edit Note' : 'Create Note') }}<a href="{{ route('note.list') }}" class="float-right btn btn-primary btn-sm">{{ __('Note List') }}</a></div>

                <div class="card-body">
                    @if (session('error-message'))
                        <div class="alert alert-danger" role="alert">
                           <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ session('error-message') }}
                        </div>
                    @endif

                    <form action="{{ isset($note) ? route('note.store', $note->id) : route('note.store') }}" method="post">
                        @csrf

                        <div class="form-group">
                            <label for="title">{{ __('Title') }}*</label>
                            <input type="text" name="title" id="title" placeholder="Title" class="form-control @error('title') is-invalid @enderror" value="{{ isset($note) ? $note->title : '' }}">

                            @error('title')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>


                        <div class="form-group">
                            <label for="content">{{ __('Content') }}</label>
                            <textarea name="content" id="content" rows="10" class="form-control @error('content') is-invalid @enderror" id="content">{{ isset($note) ? $note->content : '' }}</textarea>
                        </div>
                    
                    <div class="form-group">
                    <label for="content">{{ __('Categories') }} <small>{{ __('(select one or more category if applicable )') }}</small></label>
                            <div class="row">
                                    @forelse($categories as $category)
                                             <div class="col-md-6">
                                                <div class="form-check">
                                                    <input class="form-check-input" type="checkbox" name="note_categories[]" id="note_category{{ $category->id }}" value="{{ $category->id }}" {{ isset($note) ? (in_array($category->id, $existingNoteCategories)?'checked':'') : '' }}>

                                                    <label class="form-check-label" for="note_category{{ $category->id }}">
                                                        {{ __($category->name) }}
                                                    </label>
                                                </div>
                                            </div>
                                            @empty
                                            <em>No category available, click here to <a href="{{ route('category.create') }}">{{ __('Create Category') }}</a></em>
                                    @endforelse
                            </div>
                   </div>

                        <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
                    </form>

                </div>

            </div>

        </div>

    </div>

</div>

@endsection

resources/views/note/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Notes') }}<a href="{{ route('note.create') }}" class="float-right btn btn-primary btn-sm">{{ __('Create Note') }}</a></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                              {{ session('status') }}
                        </div>
                    @endif

                    <ul class="list-group list-group-flush">
                        @foreach ($notes as $note)
                            <li class="list-group-item">
                                <span class="float-left">
                                   <a href="{{ route('note.view', $note->id) }}">{{ $note->title }}</a>
                                </span>
                               <span class="float-right">
                                @foreach($note->categories as $category)
                                  <small>** {{$category->name}}</small>
                                 @endforeach
                                 </span>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection